### ISSUE TITLE
OnPageSelected   in Design Support Library Sample

### ISSUE THREAD

**Issue by jorgenstorlie** [jamesmontemagno/Xam.NavDrawer#16]
I try to use som of the code from
Design Support Library Sample
I need to handle the selection of tabs in the viewpager.
tabs.OnPageSelected > do something

Do you have a sample on that?

Befor I used PagerSlidingTabStrip-for-Xamarin.Android where you had added implementation of some of the events.

**Comment by jamesmontemagno** [comment]
Please see the documentation: https://developer.android.com/reference/android/support/design/widget/TabLayout.html#setOnTabSelectedListener(android.support.design.widget.TabLayout.OnTabSelectedListener)
