### ISSUE TITLE
How to solve the Layout "show error" issue?

### ISSUE THREAD

**Issue by arkilis** [jamesmontemagno/Xam.NavDrawer#22]
Thanks.

![navdrawer droid resources menu nav_menu xml visual studio community 2017 for mac 2017-09-10 08-40-26](https://user-images.githubusercontent.com/1528028/30244565-bcad9f96-9603-11e7-8b3f-d1717248f50a.png)

**Comment by jamesmontemagno** [comment]
this is the designer, not the library. you can open a bug in the xamarin bugzilla tracker.
