### ISSUE TITLE
Any plans to use a tab navigation that support material design?

### ISSUE THREAD

**Issue by jorgenstorlie** [jamesmontemagno/Xam.NavDrawer#3]
something like this:

https://github.com/jpardogo/PagerSlidingTabStrip

**Comment by jamesmontemagno** [comment]
Updated source code @jorgenstorlie 

I ported and release the PagerSlidingTabStrip as a Nuget and you will find it on github here: https://www.nuget.org/packages/Refractored.PagerSlidingTabStrip/  and https://github.com/jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android
