### ISSUE TITLE
Toolbar on top of navigation drawer

### ISSUE THREAD

**Issue by escobar5** [jamesmontemagno/Xam.NavDrawer#6]
When the navigation drawer is open, it hides the toolbar, is there a way to not hide the toolbar? Can the navigation drawer appear behind the toolbar?

Thanks

**Comment by jamesmontemagno** [comment]
This is new material design paradigm. You can change your app to not use the new Toolbar and use the old action bar. In this case you need to inherit from ActionBarActivity instead of base activity and then in your styles change windowActionBar to true

That should work.

**Comment by escobar5** [comment]
Thank you!
