### ISSUE TITLE
Toolbar size if I prevent activity to be recreated on rotate is wrong

### ISSUE THREAD

**Issue by jorgenstorlie** [jamesmontemagno/Xam.NavDrawer#8]
I changed Homeactivity

[Activity (Label = "Home", MainLauncher = true, LaunchMode = LaunchMode.SingleTop, Icon = "@drawable/ic_launcher", ConfigurationChanges = (ConfigChanges.Orientation | ConfigChanges.ScreenSize))]

after that the toolbar size is wrong then you rotate the app.

Any easy fix?

**Comment by jamesmontemagno** [comment]
Toolbar should be small when rotated as I set to the size: https://github.com/jamesmontemagno/Xam.NavDrawer/blob/master/Material%20(Lollipop%20Style)/AppCompat%20v14%2B/Resources/Layout/toolbar.axml

do you have a screenshot. I am not sure which you are testing.

**Comment by jorgenstorlie** [comment]
Hello

 

Here are screenshots

 

Your sample works

 

I have modified the code:

 

[Activity (Label = "Home", MainLauncher = true, LaunchMode = LaunchMode.SingleTop, Icon = "@drawable/ic_launcher", ConfigurationChanges = (ConfigChanges.Orientation | ConfigChanges.ScreenSize))]

 

To prevent the activity to be recreated on rotate, this makes the toolbar not to resize.

 

Jørgen

**Comment by jorgenstorlie** [comment]
![wrong](https://cloud.githubusercontent.com/assets/2240379/7698932/779d22e8-fe14-11e4-8b6d-bebb614e8602.png)

**Comment by jorgenstorlie** [comment]
Do you have any good solution on this?

**Comment by jamesmontemagno** [comment]
Your toolbar.axml should set:

    android:layout_height="?attr/actionBarSize"
    android:minHeight="?attr/actionBarSize"

see: https://code.google.com/p/android/issues/detail?id=170707

and

https://code.google.com/p/android/issues/detail?id=77874

Working as intentded on my sample.

**Comment by jorgenstorlie** [comment]
the problem is if you add this:


[Activity (Label = "Home", MainLauncher = true, LaunchMode = LaunchMode.SingleTop, Icon = "@drawable/ic_launcher", ConfigurationChanges = (ConfigChanges.Orientation | ConfigChanges.ScreenSize))]

to prevent the activity to be recreated on rotate, the toolbar does not resize anymore.

**Comment by jamesmontemagno** [comment]
This would be a bug in android and should be reported against https://code.google.com/p/android/issues/list

Best,
James

**Comment by jorgenstorlie** [comment]
Same as this:

https://code.google.com/p/android/issues/detail?id=172141&q=toolbar&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars
